name: Fetch Discord Content
# 觸發條件：
# 1. schedule: 每天 UTC 時間 0 點執行一次
# 2. workflow_dispatch: 允許你手動在 Actions 頁面觸發
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 授予 workflow 寫入 repository 內容的權限
    steps:
      # 步驟 1: Checkout 你的程式碼
      - name: Checkout repository
        uses: actions/checkout@v3
      # 步驟 2: 設定 Python 環境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # 步驟 3: 安裝 Python 依賴套件
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      # 步驟 4: 執行你的 Python 腳本
      - name: Run fetch script
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_INVITE_LINK: ${{ secrets.DISCORD_INVITE_LINK }}
        run: python fetch_discord.py
      # 步驟 5: 將變更的檔案 (index.html) commit 並 push 回倉庫
      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: 自動更新 Discord 內容'
          file_pattern: 'index.html'